/**
 * Catálogo de las insignias automáticas (docs/insignias.md §2): la única fuente de keys, nombres, textos, niveles,
 * umbrales, rarezas estimadas, forma e ícono. Lo leen la app (textos, progreso, galería) y el motor (umbrales,
 * parámetros y qué evaluador corre cada una). Todo puro, sin React: entra en el bundle de Deno.
 *
 * Todos los deportes están abiertos desde el primer día (no hay lanzamiento por fases).
 *
 * Plantillas de texto: `{n}` es el valor (el umbral del nivel, o el valor real que guarda `context.values.n`) y el
 * resto sale de la evidencia o del deporte (ver `PLACEHOLDERS`). Nunca se nombra al rival.
 *
 * Historial de umbrales (§3.8): cada cambio se anota aquí con fecha y motivo. Subir un umbral solo afecta lo que se
 * gane después; lo ya ganado se queda.
 * - 2026-09-29: valores iniciales del diseño.
 */
import { SPORT_FAMILY, type SportId } from '../sports/types';
import type {
  BadgeAlt,
  BadgeCategory,
  BadgeDef,
  BadgeSport,
  BadgesAuto,
  ByVariant,
  EvaluatorId,
  JobKind,
  Level,
  LevelDef,
  Rarity,
  RarityTarget,
  Variant,
} from './types';

// ---------------------------------------------------------------------------------------------------------
// Ayudas para escribir el catálogo

const ALL_SPORTS = Object.keys(SPORT_FAMILY) as SportId[];
const RACKET: readonly SportId[] = ['padel', 'tennis', 'pickleball', 'table_tennis'];
const TEAM: readonly SportId[] = ['basketball', 'football', 'futsal'];
const FOOTBALL: readonly SportId[] = ['football', 'futsal'];
/** Deportes con título del mes y del año (una tabla individual que el servidor puede recalcular). */
const FIGURE: readonly SportId[] = ['bowling', 'padel', 'tennis', 'pickleball', 'table_tennis', 'golf'];
/** Deportes con progreso contra la línea base (§1.7.6). */
const PROGRESS: readonly SportId[] = ['bowling', 'padel', 'tennis', 'pickleball', 'table_tennis', 'golf', 'swimming'];

/** Niveles 1, 2, 3… con su umbral y la rareza de cada uno ('C PC R E'). */
function tiers(rarities: string, thresholds: readonly ByVariant<number>[], extra: readonly (Partial<LevelDef> | undefined)[] = []): LevelDef[] {
  const r = rarities.split(' ') as Rarity[];
  if (r.length !== thresholds.length) throw new Error('catálogo: rarezas y umbrales no cuadran');
  return thresholds.map((threshold, i) => ({ level: (i + 1) as Level, threshold, rarity: r[i], ...extra[i] }));
}

/** Un solo nivel (el 0, «única»). */
const one = (rarity: ByVariant<RarityTarget>, threshold?: ByVariant<number>): LevelDef[] => [
  threshold === undefined ? { level: 0, rarity } : { level: 0, rarity, threshold },
];

/** Podio: oro = 1.º (nivel 3), plata = 2.º (nivel 2), bronce = 3.º (nivel 1). El umbral es el puesto. */
const podium = (gold: Rarity, silver: Rarity, bronze: Rarity): LevelDef[] => [
  { level: 1, threshold: 3, rarity: bronze },
  { level: 2, threshold: 2, rarity: silver },
  { level: 3, threshold: 1, rarity: gold },
];

const units = (singular: string, plural: string) => [singular, plural] as const;

// ---------------------------------------------------------------------------------------------------------
// 2.1 General y multideporte

const GENERAL: BadgeDef[] = [
  {
    key: 'debut',
    group: 'general',
    sports: ALL_SPORTS,
    scope: 'cuenta',
    period: 'siempre',
    category: 'bienvenida',
    shape: 'hex',
    icon: 'sport',
    name: {
      default: 'Debut',
      bowling: 'Primera línea',
      padel: 'Debut en la cancha',
      tennis: 'Debut en la cancha',
      pickleball: 'Debut en la cancha',
      table_tennis: 'Debut en la mesa',
      basketball: 'Debut en la cancha',
      football: 'Debut en la cancha',
      futsal: 'Debut en la cancha',
      golf: 'Primera ronda',
      swimming: 'Primera prueba',
    },
    // Golf y natación cuentan en femenino (ronda, prueba): «tu primera», y en natación se nada.
    description: {
      default: '¡Arrancaste! Tu primer {unidad} de {deporte} ya cuenta.',
      golf: '¡Arrancaste! Tu primera ronda de golf ya cuenta.',
      swimming: '¡Arrancaste! Tu primera prueba de natación ya cuenta.',
    },
    how: {
      default: 'Juega tu primer {unidad} de {deporte} en una liga.',
      golf: 'Juega tu primera ronda de golf en una liga.',
      swimming: 'Nada tu primera prueba en una liga.',
    },
    compare: 'none',
    levels: one('C'),
    evaluator: 'debut',
  },
  {
    key: 'month_streak',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'constancia',
    shape: 'circle',
    icon: 'flame',
    name: 'Constancia',
    description: '{n} meses seguidos jugando. ¡Tú no paras!',
    how: 'Juega al menos 2 días cada mes (una ronda de golf o un encuentro de natación bastan), {n} meses seguidos.',
    unit: units('mes', 'meses'),
    compare: 'gte',
    levels: tiers('C PC R E L', [3, 6, 12, 24, 36]),
    params: { minWeightedDays: 2, wildcardWindow: 12 },
    evaluator: 'month_streak',
  },
  {
    key: 'mileage',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'lealtad',
    shape: 'hex',
    icon: 'footprints',
    name: 'Kilometraje',
    description: '{n} días jugando en MatchMate.',
    how: 'Suma {n} días jugando. Un día de golf o de natación vale 2.',
    unit: units('día', 'días'),
    compare: 'gte',
    levels: tiers('PC R E', [50, 150, 300]),
    params: { maxWeightedPerWeek: 4, settleHours: 48 },
    evaluator: 'account_activity',
  },
  {
    key: 'strong_start',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'bienvenida',
    shape: 'hex',
    icon: 'rocket',
    name: 'Arranque con todo',
    description: "Jugaste {n} días en tu primer mes. ¡Llegaste pa' quedarte!",
    how: 'Juega {n} días distintos en tus primeros 30 días.',
    unit: units('día', 'días'),
    compare: 'gte',
    levels: one('C', 4),
    params: { windowDays: 30 },
    evaluator: 'account_activity',
  },
  {
    key: 'multisport',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'multideporte',
    shape: 'hex',
    icon: 'infinity',
    name: 'Multideporte',
    levelNames: { 1: 'Doble vía', 2: 'Todoterreno', 3: 'Pentatleta' },
    description: 'Juegas {n} deportes en MatchMate: {deportes}.',
    how: 'Juega {n} deportes distintos, al menos 3 días en cada uno.',
    unit: units('deporte', 'deportes'),
    compare: 'gte',
    levels: tiers('PC R E', [2, 3, 5]),
    params: { minDaysPerSport: 3 },
    evaluator: 'account_activity',
  },
  {
    key: 'three_worlds',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'multideporte',
    shape: 'hex',
    icon: 'sparkles',
    name: 'Tres mundos',
    description: 'Juegas de todo: series, raqueta y equipo.',
    how: 'Juega al menos 3 días en un deporte de series (boliche, golf o natación), en uno de raqueta y en uno de equipo.',
    compare: 'none',
    levels: one('E'),
    params: { minDaysPerSport: 3 },
    evaluator: 'account_activity',
  },
  {
    key: 'anniversary',
    group: 'general',
    sports: 'all',
    scope: 'cuenta',
    period: 'aniversario',
    category: 'lealtad',
    shape: 'circle',
    icon: 'cake',
    name: 'Aniversario',
    description: '{n} años jugando en MatchMate. ¡Gracias por estar!',
    levelDescriptions: { 1: 'Un año jugando en MatchMate. ¡Gracias por estar!' },
    how: 'Cumple {n} año(s) en MatchMate jugando al menos 12 días en el último año.',
    unit: units('año', 'años'),
    compare: 'gte',
    levels: tiers('C PC R', [1, 2, 5]),
    params: { minWeightedDays: 12 },
    accountOnly: true,
    evaluator: 'account_activity',
  },
  {
    key: 'climbing',
    group: 'general',
    sports: ['bowling', 'golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'mejora',
    shape: 'hex',
    icon: 'mountain',
    name: 'Subiendo',
    description: {
      bowling: 'Tu promedio subió {n} pinos desde que empezaste. ¡Se nota el trabajo!',
      golf: 'Bajaste {n} golpes desde tus primeras rondas.',
    },
    how: {
      bowling: 'Sube {n} pinos entre la media de tus primeros 18 juegos y la de tus últimos 18.',
      golf: 'Baja {n} golpes entre el diferencial de tus primeras 5 rondas de 18 hoyos y el de tus últimas 5.',
    },
    unit: { bowling: units('pino', 'pinos'), golf: units('golpe', 'golpes') },
    compare: 'gte',
    levels: tiers('PC R E', [
      { bowling: 5, golf: 2 },
      { bowling: 10, golf: 4 },
      { bowling: 20, golf: 6 },
    ]),
    params: { window: { bowling: 18, golf: 5 }, minCount: { bowling: 36, golf: 10 } },
    evaluator: 'climbing',
  },
  {
    key: 'event_podium',
    group: 'general',
    sports: ['bowling', 'padel', 'tennis', 'pickleball', 'table_tennis', 'basketball', 'football', 'futsal', 'golf'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'trophy',
    name: 'Podio',
    levelNames: { 3: 'Primer lugar', 2: 'Segundo lugar', 1: 'Tercer lugar' },
    description: 'Te subiste al podio de {evento}.',
    levelDescriptions: { 3: 'Ganaste {evento}.', 2: 'Quedaste en segundo lugar en {evento}.', 1: 'Te subiste al podio de {evento}.' },
    how: 'Termina entre los tres primeros de un torneo de tu liga, con campo suficiente.',
    compare: 'place',
    levels: podium('R', 'R', 'PC'),
    params: { minPlayers: { bowling: 6 }, minAccounts: { golf: 4 }, graceHours: { default: 48, bowling: 72, golf: 24 } },
    repeatable: true,
    title: true,
    evaluator: 'event_podium',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.2 Boliche

const BOWLING: BadgeDef[] = [
  {
    key: 'bowling_games',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Líneas jugadas',
    description: 'Ya llevas {n} juegos que cuentan.',
    how: 'Juega {n} juegos que cuenten (con foto o aprobados).',
    unit: units('juego', 'juegos'),
    compare: 'gte',
    levels: tiers('C PC R E', [30, 100, 300, 1000]),
    params: { maxPerDay: 10 },
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_breakthrough',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'mejora',
    shape: 'hex',
    icon: 'trending-up',
    name: 'Rompe barreras',
    description: "Pasaste los {n} por primera vez. ¡Eso va pa'rriba!",
    how: 'Tira un juego de {n} o más.',
    unit: units('pino', 'pinos'),
    compare: 'gte',
    levels: tiers('C C PC', [125, 150, 175]),
    privateByDefault: true,
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_club',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'crown',
    name: 'Club de los 200',
    levelNames: { 1: 'Club 200', 2: 'Club 225', 3: 'Club 250', 4: 'Club 275' },
    description: 'Entraste al club de los {n}.',
    how: 'Tira un juego de {n} o más (desde 250, con foto).',
    unit: units('pino', 'pinos'),
    compare: 'gte',
    levels: tiers('PC R E L', [200, 225, 250, 275], [undefined, undefined, { strict: true }, { strict: true }]),
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_perfect_game',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'gem',
    name: 'Juego perfecto',
    description: '300. Doce strikes seguidos. Leyenda.',
    how: 'Tira un juego perfecto de 300 con foto del marcador. Tu liga lo confirma.',
    compare: 'gte',
    levels: [{ level: 0, threshold: 300, rarity: 'L', strict: true }],
    repeatable: true,
    aval: true,
    evaluator: 'bowling_game',
  },
  {
    key: 'bowling_series',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'zap',
    name: 'Serie de tres',
    description: 'Sumaste {n} en tres juegos seguidos.',
    how: 'Suma {n} o más en tres juegos seguidos de un mismo evento.',
    unit: units('pino', 'pinos'),
    compare: 'gte',
    levels: tiers('PC R E', [500, 575, 650], [undefined, undefined, { strict: true }]),
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_over_average',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'mejora',
    shape: 'hex',
    icon: 'rocket',
    name: 'Por encima de ti',
    description: 'Tiraste {n} pinos por encima de tu promedio.',
    how: 'Tira un juego {n} pinos por encima de tu promedio (se mide con tus últimos 30 juegos; necesitas 12).',
    unit: units('pino', 'pinos'),
    compare: 'gte',
    levels: tiers('C PC R', [25, 40, 60], [undefined, undefined, { strict: true }]),
    params: { minBaseGames: 12, baseWindow: 30 },
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_strike_streak',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'flame',
    name: 'Racha de strikes',
    levelNames: { 1: 'Pavo', 2: 'Six-pack', 3: 'Nueve seguidos' },
    description: 'Metiste {n} strikes seguidos en un juego.',
    how: 'Mete {n} strikes seguidos en un juego anotado bola por bola.',
    unit: units('strike', 'strikes'),
    compare: 'gte',
    levels: tiers('PC E L', [3, 6, 9], [undefined, undefined, { strict: true }]),
    evaluator: 'bowling_career',
  },
  {
    key: 'bowling_clean_game',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'badge-check',
    name: 'Cero abiertos',
    description: 'Un juego entero sin dejar cuadro abierto.',
    how: 'Termina un juego anotado bola por bola sin dejar ningún cuadro abierto.',
    compare: 'none',
    levels: one('R'),
    repeatable: true,
    evaluator: 'bowling_game',
  },
  {
    key: 'bowling_split',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'crosshair',
    name: 'Split convertido',
    description: 'Te paraste frente a un split y lo tumbaste.',
    how: 'Convierte un split en un juego donde anotes qué pinos tumbas.',
    compare: 'none',
    levels: one('R'),
    repeatable: true,
    evaluator: 'bowling_game',
  },
  {
    key: 'bowling_seven_ten',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'target',
    name: 'El 7-10',
    description: 'Convertiste el 7-10. Casi nadie lo logra.',
    how: 'Convierte el 7-10 con foto del marcador y los pinos anotados. Tu liga lo confirma.',
    compare: 'none',
    levels: [{ level: 0, rarity: 'L', strict: true }],
    repeatable: true,
    aval: true,
    evaluator: 'bowling_game',
  },
  {
    key: 'bowling_category_win',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'medal',
    name: 'Mejor de tu categoría',
    description: 'Nadie te ganó en la categoría {categoria} de {evento}.',
    how: 'Gana tu categoría (A, B, C o D) en un torneo con 4 o más jugadores en ella.',
    compare: 'none',
    levels: one('PC'),
    params: { minInCategory: 4, sandbagPins: 15 },
    repeatable: true,
    title: true,
    evaluator: 'bowling_event',
  },
  {
    key: 'bowling_team_win',
    group: 'bowling',
    sports: ['bowling'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'users-round',
    name: 'Título por equipos',
    description: 'Tu equipo ganó {evento}.',
    how: 'Gana un torneo por equipos con 3 o más equipos.',
    compare: 'none',
    levels: one('R'),
    params: { minTeams: 3, minMembers: 2 },
    repeatable: true,
    title: true,
    evaluator: 'bowling_event',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.3 Raqueta: pádel, tenis, pickleball y ping pong

const RACKET_BADGES: BadgeDef[] = [
  {
    key: 'racket_matches',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Partidos jugados',
    description: 'Ya llevas {n} partidos de {deporte}.',
    how: 'Juega {n} partidos que cuenten (americano incluido; sin W.O.).',
    unit: units('partido', 'partidos'),
    compare: 'gte',
    levels: tiers('C PC R E', [10, 30, 75, 150]),
    params: { maxPerDay: 4 },
    evaluator: 'racket_career',
  },
  {
    key: 'racket_wins',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'award',
    name: 'Victorias',
    description: 'Ya llevas {n} victorias.',
    how: {
      default: 'Gana {n} partidos a sets que confirme el rival (máximo 3 por mes contra el mismo).',
      table_tennis: 'Gana {n} partidos que confirme el rival (máximo 3 por mes contra el mismo).',
    },
    unit: units('victoria', 'victorias'),
    compare: 'gte',
    levels: tiers('C PC R E', [5, 15, 40, 100]),
    params: { maxPerRivalMonth: 3 },
    evaluator: 'racket_career',
  },
  {
    key: 'racket_win_streak',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'circle',
    icon: 'flame',
    name: 'Racha ganadora',
    description: 'Ganaste {n} partidos seguidos.',
    how: 'Gana {n} partidos seguidos contra al menos 2 rivales distintos (3 para el oro).',
    unit: units('partido', 'partidos'),
    compare: 'gte',
    levels: tiers('PC R E', [3, 5, 8], [{ req: { rivals: 2 } }, { req: { rivals: 2 } }, { req: { rivals: 3 } }]),
    evaluator: 'racket_career',
  },
  {
    key: 'racket_bagel',
    group: 'racket',
    sports: RACKET,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'target',
    // «Zapatero»: así se dice en la República Dominicana cuando alguien pierde sin anotar (en el dominó y en la mesa).
    name: { default: 'Rosco', padel: 'Set en blanco', tennis: 'Set en blanco', pickleball: 'Juego en blanco', table_tennis: 'Zapatero' },
    description: { default: 'Ganaste un set 6-0.', pickleball: 'Ganaste un juego sin que te anotaran.', table_tennis: 'Ganaste un juego 11-0.' },
    how: {
      default: 'Gana un set sin ceder un juego, en un partido confirmado.',
      pickleball: 'Gana un juego sin que el rival anote, en un partido confirmado.',
      table_tennis: 'Gana un juego 11-0 en un partido confirmado.',
    },
    compare: 'none',
    levels: one({ padel: 'PC', tennis: 'PC', pickleball: 'R', table_tennis: 'R' }),
    repeatable: true,
    evaluator: 'racket_match',
  },
  {
    key: 'racket_comeback',
    group: 'racket',
    sports: RACKET,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'repeat',
    name: 'Remontada',
    description: {
      default: 'Perdiste el primer set y le diste la vuelta.',
      pickleball: 'Perdiste el primer juego y le diste la vuelta.',
      table_tennis: 'Ibas 0-2 en juegos y le diste la vuelta.',
    },
    how: {
      default: 'Gana un partido después de perder el primer set, sin retiro.',
      pickleball: 'Gana un partido después de perder el primer juego, sin retiro.',
      table_tennis: 'Gana un partido al mejor de 5 o 7 después de perder los dos primeros juegos, sin retiro.',
    },
    compare: 'none',
    levels: one('PC'),
    // Sets (o juegos) perdidos al empezar: en ping pong, los dos primeros (0-2 en juegos).
    params: { down: { default: 1, table_tennis: 2 } },
    repeatable: true,
    evaluator: 'racket_match',
  },
  {
    key: 'racket_tiebreaks',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'zap',
    name: { default: 'Sangre fría', pickleball: 'Al filo', table_tennis: 'Al filo' },
    description: {
      default: 'Ganaste {n} tie-breaks.',
      pickleball: 'Ganaste {n} juegos que se fueron más allá de {tope}.',
      table_tennis: 'Ganaste {n} juegos después del 10-10.',
    },
    how: {
      default: 'Gana {n} tie-breaks en partidos confirmados.',
      pickleball: 'Gana {n} juegos que se vayan más allá de los puntos del juego.',
      table_tennis: 'Gana {n} juegos que se vayan más allá del 10-10 (12-10, 13-11…).',
    },
    unit: { default: units('tie-break', 'tie-breaks'), pickleball: units('juego', 'juegos'), table_tennis: units('juego', 'juegos') },
    compare: 'gte',
    levels: tiers('PC R E', [3, 10, 25]),
    evaluator: 'racket_career',
  },
  {
    key: 'racket_upset',
    group: 'racket',
    sports: RACKET,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'rocket',
    name: 'Batacazo',
    description: 'Le ganaste a alguien con mucho mejor récord que tú.',
    how: 'Gánale a alguien con 10 o más partidos y al menos 25 puntos más de % de victorias que tú.',
    compare: 'none',
    levels: one('R'),
    params: { minRivalMatches: 10, minOwnMatches: 5, pctGap: 25 },
    repeatable: true,
    evaluator: 'racket_match',
  },
  {
    key: 'racket_partners',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'handshake',
    name: 'Buena química',
    description: 'Has ganado con {n} compañeros distintos.',
    how: 'Gana partidos de dobles con {n} compañeros distintos.',
    unit: units('compañero', 'compañeros'),
    compare: 'gte',
    levels: tiers('PC R', [3, 8]),
    evaluator: 'racket_career',
  },
  {
    key: 'racket_ladder_climber',
    group: 'racket',
    sports: RACKET,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'trending-up',
    name: 'Escalando',
    description: 'Ganaste {n} retos subiendo en la escalera.',
    levelDescriptions: { 1: 'Ganaste tu primer reto subiendo en la escalera.' },
    how: 'Gana {n} retos como retador en la escalera, en partidos confirmados.',
    unit: units('reto', 'retos'),
    compare: 'gte',
    levels: tiers('PC R E', [1, 5, 15]),
    evaluator: 'racket_career',
  },
  {
    key: 'racket_night_champion',
    group: 'racket',
    sports: ['padel', 'pickleball'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'moon-star',
    name: 'Figura de la noche',
    description: 'Nadie sumó más puntos que tú en la noche de {formato}.',
    how: 'Suma más puntos que nadie en una noche de americano o mexicano de 8 o más jugadores.',
    compare: 'none',
    levels: one('R'),
    params: { minPlayers: 8, minAccounts: 6, minWriters: 2, closeHours: 24 },
    repeatable: true,
    title: true,
    evaluator: 'racket_night',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.4 Equipos: compartidas por baloncesto, fútbol y sala

const TEAM_BADGES: BadgeDef[] = [
  {
    key: 'team_matches',
    group: 'team',
    sports: TEAM,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Partidos jugados',
    description: 'Ya llevas {n} partidos.',
    how: 'Juega {n} partidos en los que salgas en la alineación o el acta.',
    unit: units('partido', 'partidos'),
    compare: 'gte',
    levels: tiers('C PC R E', [5, 15, 40, 100]),
    evaluator: 'team_career',
  },
  {
    key: 'team_wins',
    group: 'team',
    sports: TEAM,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'award',
    name: 'Victorias',
    description: 'Tu equipo ha ganado {n} partidos contigo en cancha.',
    how: 'Gana {n} partidos con tu equipo, jugando tú (máximo 2 por mes contra el mismo equipo).',
    unit: units('victoria', 'victorias'),
    compare: 'gte',
    levels: tiers('C PC R E', [5, 15, 40, 100]),
    params: { maxPerTeamMonth: 2 },
    evaluator: 'team_career',
  },
  {
    key: 'team_unbeaten',
    group: 'team',
    sports: TEAM,
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'circle',
    icon: 'flame',
    name: { default: 'Invicto', basketball: 'Racha ganadora' },
    description: { default: '{n} partidos seguidos sin perder contigo en cancha.', basketball: '{n} partidos seguidos ganando contigo en cancha.' },
    how: { default: 'Juega {n} partidos seguidos sin perder.', basketball: 'Gana {n} partidos seguidos jugando tú.' },
    unit: units('partido', 'partidos'),
    compare: 'gte',
    levels: tiers('PC R E', [3, 5, 8]),
    evaluator: 'team_career',
  },
  {
    key: 'team_comeback',
    group: 'team',
    sports: TEAM,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'repeat',
    name: 'Remontada',
    description: 'Tu equipo iba perdiendo y lo ganó.',
    how: {
      default: 'Gana un partido que tu equipo perdía al medio tiempo o por 2 goles.',
      basketball: 'Gana un partido que tu equipo perdía por 8 o más al medio tiempo.',
    },
    compare: 'none',
    levels: one('R'),
    params: { deficit: { basketball: 8, football: 2, futsal: 2 } },
    repeatable: true,
    excludeVariants: ['basketball3x3'],
    evaluator: 'team_match',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.5 Baloncesto (umbrales de 5x5; los de 3x3 van en `basketball3x3`)

const BASKETBALL: BadgeDef[] = [
  {
    key: 'basketball_first_basket',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'bienvenida',
    shape: 'hex',
    icon: 'sport',
    name: 'Tu primera canasta',
    description: '¡Anotaste tu primer punto!',
    how: 'Anota tu primer punto en un partido.',
    compare: 'gte',
    levels: one('C', 1),
    evaluator: 'basketball_career',
  },
  {
    key: 'basketball_points_game',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'flame',
    name: 'Noche de anotación',
    description: 'Metiste {n} puntos en un partido.',
    how: 'Mete {n} puntos en un partido.',
    unit: units('punto', 'puntos'),
    compare: 'gte',
    levels: tiers('C PC R', [
      { basketball: 10, basketball3x3: 6 },
      { basketball: 20, basketball3x3: 10 },
      { basketball: 30, basketball3x3: 14 },
    ]),
    evaluator: 'basketball_career',
  },
  {
    key: 'basketball_points',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'target',
    name: 'Punto a punto',
    description: 'Ya llevas {n} puntos.',
    how: 'Suma {n} puntos en partidos.',
    unit: units('punto', 'puntos'),
    compare: 'gte',
    levels: tiers('C PC E', [50, 250, 1000]),
    evaluator: 'basketball_career',
  },
  {
    key: 'basketball_threes_game',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'crosshair',
    name: 'Mano caliente',
    description: 'Metiste {n} triples en un partido.',
    how: 'Mete {n} triples en un partido.',
    unit: units('triple', 'triples'),
    compare: 'gte',
    levels: tiers('PC E', [3, 6]),
    excludeVariants: ['basketball3x3'],
    evaluator: 'basketball_career',
  },
  {
    key: 'basketball_threes',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'zap',
    name: 'Desde lejos',
    description: 'Ya llevas {n} triples.',
    how: 'Suma {n} triples en partidos.',
    unit: units('triple', 'triples'),
    compare: 'gte',
    levels: tiers('PC R', [10, 50]),
    excludeVariants: ['basketball3x3'],
    evaluator: 'basketball_career',
  },
  {
    key: 'basketball_triple_threat',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'sparkles',
    name: 'Triple amenaza',
    description: 'En un mismo partido anotaste de 1, de 2 y de 3, con 15 o más.',
    how: 'En un mismo partido, anota de 1, de 2 y de 3 y llega a {n} puntos.',
    compare: 'gte',
    levels: one('PC', 15),
    repeatable: true,
    excludeVariants: ['basketball3x3'],
    evaluator: 'basketball_match',
  },
  {
    key: 'basketball_clean_hands',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'liga',
    period: 'evento',
    category: 'juego_limpio',
    shape: 'square',
    icon: 'hand-heart',
    name: 'Manos limpias',
    description: '{n} puntos o más sin cometer faltas.',
    how: 'Anota {n} puntos o más en un partido sin cometer faltas.',
    compare: 'gte',
    levels: one('PC', { basketball: 12, basketball3x3: 8 }),
    params: { minMatchFouls: 4 },
    repeatable: true,
    evaluator: 'basketball_match',
  },
  {
    key: 'basketball_game_leader',
    group: 'basketball',
    sports: ['basketball'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'crown',
    name: 'Líder del partido',
    description: 'Nadie anotó más que tú en el partido.',
    how: 'Sé quien más anota en un partido, con {n} puntos o más.',
    compare: 'gte',
    levels: one('PC', { basketball: 10, basketball3x3: 6 }),
    params: { maxLinesChars: 2800 },
    repeatable: true,
    title: true,
    evaluator: 'basketball_match',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.6 Fútbol y sala (el deporte cambia los umbrales)

const FOOTBALL_BADGES: BadgeDef[] = [
  {
    key: 'football_first_goal',
    group: 'football',
    sports: FOOTBALL,
    scope: 'cuenta',
    period: 'siempre',
    category: 'bienvenida',
    shape: 'hex',
    icon: 'goal',
    name: 'Primer gol',
    description: '¡Tu primer gol!',
    how: 'Mete tu primer gol en un partido.',
    compare: 'gte',
    levels: one({ football: 'PC', futsal: 'C' }, 1),
    evaluator: 'football_career',
  },
  {
    key: 'football_goals',
    group: 'football',
    sports: FOOTBALL,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Gol a gol',
    description: 'Ya llevas {n} goles.',
    how: 'Mete {n} goles en partidos.',
    unit: units('gol', 'goles'),
    compare: 'gte',
    levels: tiers('PC R E', [
      { football: 5, futsal: 10 },
      { football: 20, futsal: 40 },
      { football: 50, futsal: 100 },
    ]),
    evaluator: 'football_career',
  },
  {
    key: 'football_goals_in_match',
    group: 'football',
    sports: FOOTBALL,
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'flame',
    name: 'Noche goleadora',
    levelNames: {
      1: { football: 'Doblete', futsal: 'Hat-trick' },
      2: { football: 'Hat-trick', futsal: 'Póker' },
      3: { football: 'Póker', futsal: 'Manita' },
      4: { football: 'Manita', futsal: 'Media docena' },
    },
    description: '¡{nivel}! {n} goles en un partido.',
    how: 'Mete {n} goles en un mismo partido.',
    unit: units('gol', 'goles'),
    compare: 'gte',
    levels: tiers('PC R E L', [
      { football: 2, futsal: 3 },
      { football: 3, futsal: 4 },
      { football: 4, futsal: 5 },
      { football: 5, futsal: 6 },
    ]),
    evaluator: 'football_career',
  },
  {
    key: 'football_assists',
    group: 'football',
    sports: FOOTBALL,
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'handshake',
    name: 'Pase gol',
    description: 'Ya llevas {n} asistencias.',
    how: 'Da {n} asistencias de gol (cuentan las que anota el acta).',
    unit: units('asistencia', 'asistencias'),
    compare: 'gte',
    levels: tiers('PC R', [
      { football: 5, futsal: 10 },
      { football: 20, futsal: 30 },
    ]),
    evaluator: 'football_career',
  },
  {
    key: 'football_clean_sheet',
    group: 'football',
    sports: FOOTBALL,
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'badge-check',
    name: 'Valla invicta',
    description: 'Terminaste {n} partidos sin recibir goles.',
    levelDescriptions: { 1: 'Terminaste un partido sin recibir goles.' },
    how: 'Juega de portero y termina {n} partidos sin recibir goles.',
    unit: units('partido', 'partidos'),
    compare: 'gte',
    levels: tiers('PC R E', [1, 5, 15]),
    evaluator: 'football_career',
  },
  {
    key: 'football_late_winner',
    group: 'football',
    sports: FOOTBALL,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'timer',
    name: 'Gol del triunfo',
    description: 'Metiste el gol que ganó el partido al final.',
    how: 'Mete el gol que le da la victoria a tu equipo en el último 10 % del partido o en la prórroga.',
    compare: 'none',
    levels: one('E'),
    params: { lateShare: 0.9 },
    repeatable: true,
    evaluator: 'football_match',
  },
  {
    key: 'football_shootout_win',
    group: 'football',
    sports: FOOTBALL,
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'target',
    name: 'Nervios de acero',
    description: 'Ganaron en penales.',
    how: 'Gana una tanda de penales jugando el partido.',
    compare: 'none',
    levels: one('R'),
    repeatable: true,
    evaluator: 'football_match',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.7 Golf (los de 9 hoyos van en `golf9`)

const GOLF: BadgeDef[] = [
  {
    key: 'golf_rounds',
    group: 'golf',
    sports: ['golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Rondas jugadas',
    description: 'Ya llevas {n} rondas.',
    how: 'Juega {n} rondas con tarjeta firmada (una de 9 hoyos vale media).',
    unit: units('ronda', 'rondas'),
    compare: 'gte',
    levels: tiers('C PC R', [5, 20, 60]),
    params: { maxPerDay: 1 },
    evaluator: 'golf_career',
  },
  {
    key: 'golf_birdies',
    group: 'golf',
    sports: ['golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'bird',
    name: 'Birdies',
    description: 'Ya llevas {n} birdies.',
    levelDescriptions: { 1: '¡Tu primer birdie!' },
    how: 'Haz {n} birdies (un golpe bajo par) en tarjetas firmadas.',
    unit: units('birdie', 'birdies'),
    compare: 'gte',
    levels: tiers('PC R E', [1, 10, 50], [{ strict: true }]),
    evaluator: 'golf_career',
  },
  {
    key: 'golf_eagle',
    group: 'golf',
    sports: ['golf'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'sparkles',
    name: 'Águila',
    description: 'Dos bajo par en un hoyo.',
    how: 'Haz dos golpes bajo par en un hoyo, con marcador en tu grupo.',
    compare: 'none',
    levels: one('E'),
    alts: { albatross: { name: '¡Albatros!', description: 'Tres bajo par en un hoyo.', aval: true } },
    repeatable: true,
    evaluator: 'golf_card',
  },
  {
    key: 'golf_hole_in_one',
    group: 'golf',
    sports: ['golf'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'flag-triangle-right',
    name: 'Hoyo en uno',
    description: '¡Hoyo en uno! Esto se celebra.',
    how: 'Mete la bola de un golpe, con marcador en tu grupo. Tu liga lo confirma.',
    compare: 'none',
    levels: one('L'),
    repeatable: true,
    aval: true,
    evaluator: 'golf_card',
  },
  {
    key: 'golf_break_barrier',
    group: 'golf',
    sports: ['golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'zap',
    name: 'Rompiste la barrera',
    description: 'Hiciste una ronda de {hoyos} por debajo de {n}.',
    how: 'Haz una ronda por debajo de {n} golpes, sin levantar la bola.',
    unit: units('golpe', 'golpes'),
    compare: 'lt',
    levels: tiers('C PC R E', [
      { golf: 110, golf9: 55 },
      { golf: 100, golf9: 50 },
      { golf: 90, golf9: 45 },
      { golf: 80, golf9: 40 },
    ]),
    evaluator: 'golf_career',
  },
  {
    key: 'golf_par_round',
    group: 'golf',
    sports: ['golf'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'gem',
    name: 'Ronda en par',
    description: '18 hoyos en par o mejor.',
    how: 'Juega 18 hoyos en par o mejor, sin levantar la bola. Tu liga lo confirma.',
    compare: 'none',
    levels: one('L'),
    repeatable: true,
    aval: true,
    evaluator: 'golf_card',
  },
  {
    key: 'golf_stableford',
    group: 'golf',
    sports: ['golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'star',
    name: 'Stableford',
    description: 'Sumaste {n} puntos Stableford netos.',
    how: 'Suma {n} puntos Stableford netos en una ronda.',
    unit: units('punto', 'puntos'),
    compare: 'gte',
    levels: tiers('PC R E', [
      { golf: 32, golf9: 16 },
      { golf: 36, golf9: 18 },
      { golf: 40, golf9: 20 },
    ]),
    evaluator: 'golf_career',
  },
  {
    key: 'golf_no_disaster',
    group: 'golf',
    sports: ['golf'],
    scope: 'liga',
    period: 'evento',
    category: 'constancia',
    shape: 'circle',
    icon: 'badge-check',
    name: 'Ronda sin tropiezos',
    description: '18 hoyos sin pasar de doble bogey.',
    how: 'Juega 18 hoyos sin pasar de doble bogey en ninguno.',
    compare: 'none',
    levels: one('R'),
    repeatable: true,
    evaluator: 'golf_card',
  },
  {
    key: 'golf_birdie_collection',
    group: 'golf',
    sports: ['golf'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'marcas',
    shape: 'star',
    icon: 'bird',
    name: 'Colección de birdies',
    description: 'Birdie en par 3, par 4 y par 5.',
    how: 'Haz al menos un birdie en un par 3, en un par 4 y en un par 5.',
    compare: 'none',
    levels: one('R'),
    evaluator: 'golf_career',
  },
  {
    key: 'golf_course_best',
    group: 'golf',
    sports: ['golf'],
    scope: 'liga',
    period: 'evento',
    category: 'mejora',
    shape: 'hex',
    icon: 'mountain',
    name: 'Récord personal en el campo',
    description: 'Bajaste tu mejor score en {campo}.',
    how: 'Mejora tu mejor score en un campo donde ya jugaste 2 rondas desde la misma salida.',
    compare: 'none',
    levels: one('PC'),
    params: { minPriorRounds: 2 },
    repeatable: true,
    evaluator: 'golf_card',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.8 Natación

const SWIMMING: BadgeDef[] = [
  {
    key: 'swim_races',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'sport',
    name: 'Pruebas nadadas',
    description: 'Ya llevas {n} pruebas.',
    how: 'Nada {n} pruebas en encuentros.',
    unit: units('prueba', 'pruebas'),
    compare: 'gte',
    levels: tiers('C PC R', [10, 40, 100]),
    evaluator: 'swim_career',
  },
  {
    key: 'swim_personal_best',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'mejora',
    shape: 'hex',
    icon: 'timer',
    name: 'Marca personal',
    description: 'Ya bajaste tu marca personal {n} veces.',
    levelDescriptions: { 1: 'Bajaste tu marca en {prueba}.' },
    how: 'Baja tu mejor tiempo en una prueba que ya nadaste, {n} veces.',
    unit: units('marca', 'marcas'),
    compare: 'gte',
    levels: tiers('C PC R', [1, 5, 20]),
    evaluator: 'swim_career',
  },
  {
    key: 'swim_big_drop',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'mejora',
    shape: 'hex',
    icon: 'zap',
    name: 'Bajón de tiempo',
    description: 'Mejoraste tu marca un {n} % de un golpe.',
    how: 'Baja tu marca un {n} % de una vez (contra una marca de hace 3 semanas o más).',
    compare: 'gte',
    levels: tiers('C PC R', [2, 4, 7]),
    params: { minDaysSincePrevious: 21 },
    evaluator: 'swim_career',
  },
  {
    key: 'swim_four_strokes',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'waves',
    name: 'Los cuatro estilos',
    description: 'Nadaste libre, espalda, pecho y mariposa en competencia.',
    how: 'Nada al menos una prueba de libre, de espalda, de pecho y de mariposa.',
    compare: 'none',
    levels: one('PC'),
    evaluator: 'swim_career',
  },
  {
    key: 'swim_distance',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'hitos',
    shape: 'hex',
    icon: 'anchor',
    name: 'Fondista',
    description: 'Completaste {n} m libre en competencia.',
    how: 'Completa una prueba de {n} m libre o más.',
    unit: units('metro', 'metros'),
    compare: 'gte',
    levels: tiers('R E L', [400, 800, 1500]),
    evaluator: 'swim_career',
  },
  {
    key: 'swim_medal',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'liga',
    period: 'evento',
    category: 'resultados',
    shape: 'shield',
    icon: 'medal',
    name: 'Medalla',
    levelNames: { 3: 'Oro', 2: 'Plata', 1: 'Bronce' },
    description: '{nivel} en {prueba}.',
    how: 'Termina entre los tres primeros de tu grupo en una prueba de un encuentro.',
    compare: 'place',
    levels: podium('PC', 'PC', 'C'),
    params: { goldMin: 3, silverMin: 4, bronzeMin: 5 },
    repeatable: true,
    title: true,
    evaluator: 'swim_meet',
  },
  {
    key: 'swim_record',
    group: 'swimming',
    sports: ['swimming'],
    scope: 'liga',
    period: 'evento',
    category: 'marcas',
    shape: 'star',
    icon: 'crown',
    name: 'Récord',
    levelNames: { 2: 'Récord del club', 3: 'Récord de la liga' },
    description: 'El tiempo más rápido de la liga en {prueba}.',
    levelDescriptions: { 2: 'El tiempo más rápido de tu club en {prueba}.', 3: 'El tiempo más rápido de la liga en {prueba}.' },
    how: 'Nada más rápido que todos los tiempos anteriores de tu club o de la liga en una prueba.',
    compare: 'none',
    levels: [
      { level: 2, rarity: 'R', req: { minTimes: 3, minSwimmers: 2 } },
      { level: 3, rarity: 'E', req: { minTimes: 5, minSwimmers: 3 } },
    ],
    repeatable: true,
    evaluator: 'swim_meet',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.9 Mensual (día 3 a las 00:05 por el mes anterior; ligas con peso para el mes)

const MONTHLY: BadgeDef[] = [
  {
    key: 'player_of_month',
    group: 'mensual',
    sports: FIGURE,
    scope: 'liga',
    period: 'mes',
    category: 'resultados',
    shape: 'medal',
    icon: 'star',
    name: 'Figura del mes',
    description: 'Fuiste la figura de {liga} en {mes}: {valor}.',
    how: 'Sé el mejor de tu liga en el mes (promedio, victorias o diferencial), con el mínimo de juegos.',
    compare: 'none',
    levels: one('E'),
    params: { minGames: { bowling: 9 }, minDates: { bowling: 3 }, minMatches: { padel: 4, tennis: 4, pickleball: 4, table_tennis: 4 }, minCards: { golf: 2 } },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'most_improved_month',
    group: 'mensual',
    sports: PROGRESS,
    scope: 'liga',
    period: 'mes',
    category: 'mejora',
    shape: 'medal',
    icon: 'trending-up',
    name: 'Mayor progreso del mes',
    description: 'Nadie en {liga} subió tanto como tú en {mes}: {valor}.',
    how: 'Mejora más que nadie de tu liga contra tu propio nivel del mes anterior.',
    compare: 'none',
    levels: one('R'),
    params: { minGain: { bowling: 6, padel: 8, tennis: 8, pickleball: 8, table_tennis: 8, golf: 2, swimming: 2 } },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'streak_month',
    group: 'mensual',
    sports: ['bowling', 'padel', 'tennis', 'pickleball', 'table_tennis', 'basketball', 'football', 'futsal', 'golf'],
    scope: 'liga',
    period: 'mes',
    category: 'constancia',
    shape: 'medal',
    icon: 'flame',
    name: 'Racha del mes',
    description: {
      bowling: '¡Qué racha! {n} juegos seguidos por encima de tu promedio, la mejor de {liga} en {mes}.',
      padel: '¡Qué racha! {n} victorias seguidas, la mejor de {liga} en {mes}.',
      tennis: '¡Qué racha! {n} victorias seguidas, la mejor de {liga} en {mes}.',
      pickleball: '¡Qué racha! {n} victorias seguidas, la mejor de {liga} en {mes}.',
      table_tennis: '¡Qué racha! {n} victorias seguidas, la mejor de {liga} en {mes}.',
      basketball: '{equipo} no perdió en {n} partidos seguidos, la mejor racha de {liga} en {mes}.',
      football: '{equipo} no perdió en {n} partidos seguidos, la mejor racha de {liga} en {mes}.',
      futsal: '{equipo} no perdió en {n} partidos seguidos, la mejor racha de {liga} en {mes}.',
      golf: '¡Qué racha! {n} tarjetas seguidas en tu nivel o mejor, la mejor de {liga} en {mes}.',
    },
    how: 'Ten la racha más larga de tu liga en el mes, contra tu propio nivel.',
    compare: 'none',
    levels: one('R'),
    params: { minRun: { bowling: 6, padel: 4, tennis: 4, pickleball: 4, table_tennis: 4, basketball: 4, football: 4, futsal: 4, golf: 3 }, teamShare: 0.75 },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'perfect_attendance_month',
    group: 'mensual',
    sports: ['bowling', 'padel', 'tennis', 'pickleball', 'table_tennis', 'basketball', 'football', 'futsal', 'golf'],
    scope: 'liga',
    period: 'mes',
    category: 'asistencia',
    shape: 'medal',
    icon: 'calendar-check',
    name: 'Asistencia perfecta del mes',
    description: 'No faltaste a ninguna fecha de {liga} en {mes}. ¡Tú no te pierdes una!',
    how: 'Juega todas las fechas de tu liga en el mes.',
    compare: 'none',
    levels: one('PC'),
    params: { minDates: { default: 3, golf: 2 }, minPlayers: { bowling: 4 }, minCards: { golf: 3 } },
    repeatable: true,
    evaluator: 'month_league',
  },
  {
    key: 'team_of_month',
    group: 'mensual',
    sports: TEAM,
    scope: 'liga',
    period: 'mes',
    category: 'resultados',
    shape: 'medal',
    icon: 'users-round',
    name: 'Equipo del mes',
    description: '{equipo} fue el equipo del mes en {liga}, y tú jugaste {jugados} de sus {total} partidos.',
    how: 'Juega al menos la mitad de los partidos del mejor equipo del mes.',
    compare: 'none',
    levels: one('R'),
    params: { minTeams: 4, minTeamMatches: 2, minCandidateMatches: 3, share: 0.5 },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'top_scorer_month',
    group: 'mensual',
    sports: TEAM,
    scope: 'liga',
    period: 'mes',
    category: 'resultados',
    shape: 'medal',
    icon: 'crosshair',
    name: { default: 'Bota de oro del mes', basketball: 'Más puntos del mes' },
    description: { default: 'Metiste {n} goles en {mes}, lo más de {liga}.', basketball: 'Anotaste {n} puntos en {mes}, lo más de {liga}.' },
    how: { default: 'Mete más goles que nadie de tu liga en el mes.', basketball: 'Anota más puntos que nadie de tu liga en el mes.' },
    compare: 'none',
    levels: one('E'),
    params: { minMatches: 2, minGoals: { football: 3, futsal: 4 } },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'clean_sheet_month',
    group: 'mensual',
    sports: FOOTBALL,
    scope: 'liga',
    period: 'mes',
    category: 'resultados',
    shape: 'medal',
    icon: 'badge-check',
    name: 'Valla menos vencida del mes',
    description: 'Tu portería fue la menos batida de {liga} en {mes}.',
    how: 'Juega de portero al menos 2 partidos del mes y recibe menos goles por partido que nadie.',
    compare: 'none',
    levels: one('E'),
    params: { minMatches: 2 },
    repeatable: true,
    title: true,
    evaluator: 'month_league',
  },
  {
    key: 'personal_best_month',
    group: 'mensual',
    sports: ['bowling', 'golf'],
    scope: 'cuenta',
    period: 'mes',
    category: 'mejora',
    shape: 'medal',
    icon: 'sparkles',
    name: 'Tu mejor mes',
    description: 'En {mes} tuviste tu mejor mes en {deporte}: {valor} sobre tu mejor mes anterior.',
    how: 'Ten el mejor mes de tu historia (con 3 o más meses anteriores para comparar).',
    compare: 'none',
    levels: one('PC'),
    params: { minGames: { bowling: 9 }, minCards: { golf: 2 }, minPriorMonths: 3 },
    repeatable: true,
    evaluator: 'month_account',
  },
  {
    key: 'box_top_month',
    group: 'mensual',
    sports: RACKET,
    scope: 'liga',
    period: 'cajas',
    category: 'resultados',
    shape: 'medal',
    icon: 'crown',
    name: 'Cima de tu caja',
    description: 'Terminaste en la cima de la caja {caja} en {mes}.',
    how: 'Termina primero de tu caja en el mes, con los partidos mínimos para subir.',
    compare: 'none',
    levels: one('PC'),
    params: { minPlayers: 3, minMatches: 2 },
    repeatable: true,
    title: true,
    evaluator: 'box_month',
  },
  {
    key: 'box_promoted',
    group: 'mensual',
    sports: RACKET,
    scope: 'liga',
    period: 'cajas',
    category: 'mejora',
    shape: 'medal',
    icon: 'trending-up',
    name: 'Subiste de caja',
    description: 'Subiste a la caja {caja} para {mes}.',
    how: 'Termina el mes en los puestos que suben de caja.',
    compare: 'none',
    levels: one('PC'),
    repeatable: true,
    title: true,
    evaluator: 'box_month',
  },
  {
    key: 'ladder_top',
    group: 'mensual',
    sports: RACKET,
    scope: 'liga',
    period: 'mes',
    category: 'resultados',
    shape: 'medal',
    icon: 'crown',
    name: 'Número 1',
    description: 'Cerraste {mes} en el puesto 1 de la escalera de {liga}.',
    how: 'Cierra el mes en el puesto 1 de la escalera, después de ganarlo o defenderlo en un reto.',
    compare: 'none',
    levels: one('E'),
    params: { minRungs: 8 },
    repeatable: true,
    title: true,
    evaluator: 'ladder_month',
  },
  {
    key: 'monthly_regular',
    group: 'mensual',
    sports: ALL_SPORTS,
    scope: 'cuenta',
    period: 'mes',
    category: 'constancia',
    shape: 'medal',
    icon: 'calendar-check',
    name: 'Fijo del mes',
    description: 'Jugaste {n} días de {deporte} en {mes}.',
    how: 'Juega {n} días de {deporte} en un mes (un día de golf o de natación vale 2).',
    unit: units('día', 'días'),
    compare: 'gte',
    levels: tiers('PC R E', [4, 8, 12]),
    params: { maxWeightedPerWeek: 4 },
    repeatable: true,
    highestOnly: true,
    evaluator: 'month_account',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.10 Anual (7 de enero a las 00:05 por el año anterior)

const YEARLY: BadgeDef[] = [
  {
    key: 'year_recap',
    group: 'anual',
    sports: 'all',
    scope: 'cuenta',
    period: 'anio',
    category: 'constancia',
    shape: 'medal_laurel',
    icon: 'sunrise',
    name: 'Tu {anio}',
    description: '{anio} en MatchMate: {n} días jugando, {deportes_n} deportes, {meses} meses activos. ¡Qué año!',
    how: 'Juega {n} días en el año, con al menos 6 meses activos.',
    unit: units('día', 'días'),
    compare: 'gte',
    levels: tiers('C PC R', [20, 50, 100]),
    params: { minActiveMonths: 6 },
    highestOnly: true,
    evaluator: 'year_account',
  },
  {
    key: 'full_year',
    group: 'anual',
    sports: ALL_SPORTS,
    scope: 'cuenta',
    period: 'anio',
    category: 'constancia',
    shape: 'medal_laurel',
    icon: 'sun',
    name: 'Todo el año',
    description: 'Jugaste {deporte} {n} de los 12 meses de {anio}.',
    how: 'Juega {deporte} en {n} de los 12 meses del año.',
    unit: units('mes', 'meses'),
    compare: 'gte',
    levels: one('R', 10),
    repeatable: true,
    evaluator: 'year_account',
  },
  {
    key: 'figure_of_year',
    group: 'anual',
    sports: FIGURE,
    scope: 'liga',
    period: 'anio',
    category: 'resultados',
    shape: 'medal_laurel',
    icon: 'star',
    name: 'Figura del año',
    description: 'Fuiste la figura de {liga} en {anio}.',
    how: 'Sé el mejor de tu liga en todo el año, con el mínimo de juegos.',
    compare: 'none',
    levels: one('E'),
    params: { minGames: { bowling: 36 }, minMatches: { padel: 12, tennis: 12, pickleball: 12, table_tennis: 12 }, minCards: { golf: 8 }, minAttendancePct: 40 },
    repeatable: true,
    title: true,
    evaluator: 'year_league',
  },
  {
    key: 'progress_of_year',
    group: 'anual',
    sports: PROGRESS,
    scope: 'liga',
    period: 'anio',
    category: 'mejora',
    shape: 'medal_laurel',
    icon: 'rocket',
    name: 'Mayor progreso del año',
    description: 'Nadie en {liga} progresó tanto como tú en {anio}: {valor}.',
    how: 'Mejora más que nadie de tu liga entre el principio y el final del año.',
    compare: 'none',
    levels: one('E'),
    params: {
      minGain: { bowling: 8, padel: 10, tennis: 10, pickleball: 10, table_tennis: 10, golf: 2.5 },
      minPersonalBests: { swimming: 4 },
      window: { bowling: 30, golf: 6 },
      minMatchesPerHalf: { padel: 8, tennis: 8, pickleball: 8, table_tennis: 8 },
    },
    repeatable: true,
    title: true,
    evaluator: 'year_league',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.11 Temporada (al cerrarse la temporada en `public.seasons`; ligas con peso para temporada)

const SEASON: BadgeDef[] = [
  {
    key: 'season_podium',
    group: 'temporada',
    sports: ALL_SPORTS.filter((s) => s !== 'swimming'),
    scope: 'liga',
    period: 'temporada',
    category: 'resultados',
    shape: 'shield',
    icon: 'trophy',
    name: 'Título de temporada',
    levelNames: { 3: 'Título', 2: 'Segundo lugar', 1: 'Tercer lugar' },
    description: '¡Ganaste {temporada} de {liga}!',
    levelDescriptions: {
      3: '¡Ganaste {temporada} de {liga}!',
      2: 'Terminaste en segundo lugar de {temporada} de {liga}.',
      1: 'Terminaste en tercer lugar de {temporada} de {liga}.',
    },
    how: 'Termina entre los tres primeros de la temporada, jugando al menos la mitad de las fechas.',
    compare: 'place',
    levels: podium('E', 'E', 'E'),
    alts: { torneo: { name: 'Título del torneo', description: '¡Ganaste {temporada}!' } },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'category_title',
    group: 'temporada',
    sports: ['bowling', 'swimming'],
    scope: 'liga',
    period: 'temporada',
    category: 'resultados',
    shape: 'shield',
    icon: 'medal',
    name: 'Título de categoría',
    description: 'Ganaste la categoría {categoria} de {liga} en {temporada}.',
    how: 'Termina primero de tu categoría en la temporada.',
    compare: 'none',
    levels: one('R'),
    params: { minInCategory: 4, minTotal: { bowling: 12 }, sandbagPins: { bowling: 15 } },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'season_most_improved',
    group: 'temporada',
    sports: PROGRESS,
    scope: 'liga',
    period: 'temporada',
    category: 'mejora',
    shape: 'shield',
    icon: 'trending-up',
    name: 'Mayor progreso de la temporada',
    description: 'Tu temporada en {liga}: {valor}.',
    how: 'Mejora más que nadie de tu liga entre el arranque y el final de la temporada.',
    compare: 'none',
    levels: one('E'),
    params: {
      minEligible: 6,
      minGain: { bowling: 8, padel: 10, tennis: 10, pickleball: 10, table_tennis: 10, golf: 2.5 },
      minPersonalBests: { swimming: 3 },
      minGames: { bowling: 24 },
      minPerHalf: { padel: 5, tennis: 5, pickleball: 5, table_tennis: 5, golf: 3 },
    },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'season_rookie',
    group: 'temporada',
    sports: PROGRESS,
    scope: 'liga',
    period: 'temporada',
    category: 'resultados',
    shape: 'shield',
    icon: 'sprout',
    name: 'Revelación de la temporada',
    description: 'Tu primera temporada en {deporte} y fuiste lo mejor entre los nuevos de {liga}.',
    how: 'En tu primera temporada del deporte, sé el mejor de los nuevos (con 3 o más nuevos).',
    compare: 'none',
    levels: one('R'),
    params: { minRookies: 3, minAttendancePct: 50 },
    oncePerSport: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'season_attendance',
    group: 'temporada',
    sports: ALL_SPORTS,
    scope: 'liga',
    period: 'temporada',
    category: 'asistencia',
    shape: 'shield',
    icon: 'calendar-check',
    name: 'Asistencia de temporada',
    description: 'Fuiste a {n} de las {total} fechas de {temporada}.',
    how: 'Juega el {n} % de las fechas de la temporada desde que empezaste.',
    compare: 'gte',
    levels: tiers('C PC R', [75, 90, 100]),
    params: { minDates: { bowling: 8, padel: 6, tennis: 6, pickleball: 6, table_tennis: 6, basketball: 6, football: 6, futsal: 6, golf: 4, swimming: 3 }, lineupShare: 0.8 },
    highestOnly: true,
    evaluator: 'season_league',
  },
  {
    key: 'season_top_scorer',
    group: 'temporada',
    sports: TEAM,
    scope: 'liga',
    period: 'temporada',
    category: 'resultados',
    shape: 'shield',
    icon: 'crosshair',
    name: { default: 'Bota de oro de la temporada', basketball: 'Más puntos de la temporada' },
    description: {
      default: '{n} goles en {temporada}: nadie metió más en {liga}.',
      basketball: '{n} puntos por partido en {temporada}: nadie anotó más en {liga}.',
    },
    how: { default: 'Mete más goles que nadie de tu liga en la temporada.', basketball: 'Ten el mejor promedio de puntos de tu liga en la temporada.' },
    compare: 'none',
    levels: one('E'),
    params: { minTeams: 4, share: 0.5, minGoals: { football: 3, futsal: 3 }, minMatches: { basketball: 6 } },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'season_best_keeper',
    group: 'temporada',
    sports: FOOTBALL,
    scope: 'liga',
    period: 'temporada',
    category: 'resultados',
    shape: 'shield',
    icon: 'anchor',
    name: 'Portero menos vencido',
    description: 'Tu portería fue la menos batida de {liga} en {temporada}.',
    how: 'Juega de portero al menos la mitad de los partidos de tu equipo y recibe menos goles por partido que nadie.',
    compare: 'none',
    levels: one('E'),
    params: { minTeams: 4, share: 0.5, minMatches: 6 },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'fair_play',
    group: 'temporada',
    sports: ['football', 'futsal', 'basketball', 'swimming'],
    scope: 'liga',
    period: 'temporada',
    category: 'juego_limpio',
    shape: 'square',
    icon: 'handshake',
    name: { default: 'Juego limpio', swimming: 'Estilo limpio' },
    description: {
      default: 'Una temporada entera sin roja y casi sin amarillas. ¡Así se juega!',
      basketball: 'Una temporada entera sin técnicas ni antideportivas. ¡Así se juega!',
      swimming: '{n} pruebas sin una descalificación.',
    },
    how: {
      default: 'Juega 8 o más partidos en la temporada sin rojas, con 1 amarilla como mucho.',
      basketball: 'Juega 8 o más partidos en la temporada sin faltas técnicas, antideportivas ni descalificantes.',
      swimming: 'Nada 6 o más pruebas en la temporada sin descalificaciones ni abandonos.',
    },
    compare: 'none',
    levels: one('PC'),
    params: { minMatches: { default: 8, swimming: 6 }, maxYellows: { football: 1, futsal: 1 } },
    repeatable: true,
    evaluator: 'season_league',
  },
  {
    key: 'fair_play_team',
    group: 'temporada',
    sports: TEAM,
    scope: 'liga',
    period: 'temporada',
    category: 'juego_limpio',
    shape: 'square',
    icon: 'heart-handshake',
    name: 'Equipo juego limpio',
    description: '{equipo} fue el equipo más limpio de {liga} en {temporada}.',
    how: 'Juega al menos el 40 % de los partidos del equipo con menos tarjetas o faltas de la temporada.',
    compare: 'none',
    levels: one('R'),
    params: { minTeams: 4, minMatches: 8, share: 0.4, redWeight: 3 },
    repeatable: true,
    title: true,
    evaluator: 'season_league',
  },
  {
    key: 'honor_word',
    group: 'temporada',
    sports: RACKET,
    scope: 'liga',
    period: 'temporada',
    category: 'juego_limpio',
    shape: 'square',
    icon: 'thumbs-up',
    name: 'Palabra de honor',
    description: '{n} partidos en {temporada} sin W.O. y sin reclamos perdidos. Contigo se puede contar.',
    how: 'Juega 8 o más partidos oficiales en la temporada sin dar W.O. ni perder reclamos.',
    compare: 'none',
    levels: one('PC'),
    params: { minMatches: 8 },
    repeatable: true,
    evaluator: 'season_league',
  },
];

// ---------------------------------------------------------------------------------------------------------
// 2.12 Comunidad

const COMMUNITY: BadgeDef[] = [
  {
    key: 'league_builder',
    group: 'comunidad',
    sports: 'all',
    scope: 'cuenta',
    period: 'liga',
    category: 'organizacion',
    shape: 'square',
    icon: 'users-round',
    name: 'Liga en marcha',
    description: 'Tu liga {liga} ya tiene {n} jugadores activos. ¡Armaste algo bonito!',
    how: 'Como dueño, llega a {n} jugadores que jueguen 3 días o más en tu liga.',
    unit: units('jugador', 'jugadores'),
    compare: 'gte',
    levels: tiers('R E L', [10, 25, 50]),
    params: { minDaysPerPlayer: 3, minAccounts: 6 },
    accountOnly: true,
    evaluator: 'community',
  },
  {
    key: 'season_organizer',
    group: 'comunidad',
    sports: 'all',
    scope: 'cuenta',
    period: 'temporada',
    category: 'organizacion',
    shape: 'square',
    icon: 'calendar-check',
    name: 'Temporada organizada',
    description: 'Sacaste adelante {temporada} de {liga}: {fechas} fechas y {jugadores} jugadores.',
    how: 'Organiza una temporada de 8 o más fechas y 8 o más jugadores, como dueño o admin que ayudó.',
    compare: 'none',
    levels: one('R'),
    params: { minDates: 8, minPlayers: 8, minAccounts: 4, minServiceDays: 5 },
    repeatable: true,
    accountOnly: true,
    evaluator: 'season_staff',
  },
  {
    key: 'table_crew',
    group: 'comunidad',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'voluntariado',
    shape: 'square',
    icon: 'whistle',
    name: 'Mesa técnica',
    description: '{n} días anotando y aprobando para que otros jueguen. ¡Gracias!',
    how: 'Anota, confirma o aprueba resultados de otros durante {n} días.',
    unit: units('día', 'días'),
    compare: 'gte',
    levels: tiers('PC R E', [5, 20, 60]),
    params: { minGolfCards: 4 },
    accountOnly: true,
    evaluator: 'community',
  },
  {
    key: 'captain_band',
    group: 'comunidad',
    sports: TEAM,
    scope: 'liga',
    period: 'temporada',
    category: 'liderazgo',
    shape: 'square',
    icon: 'ribbon',
    name: 'Brazalete',
    description: 'Capitaneaste a {equipo} toda la temporada: {n} partidos.',
    how: 'Sé capitán o delegado de un equipo que juegue 8 o más partidos en la temporada.',
    compare: 'none',
    levels: one('R'),
    params: { minMatches: 8, maxWalkovers: 1 },
    repeatable: true,
    evaluator: 'season_league',
  },
  {
    key: 'coach_board',
    group: 'comunidad',
    sports: ['swimming'],
    scope: 'cuenta',
    period: 'temporada',
    category: 'liderazgo',
    shape: 'square',
    icon: 'megaphone',
    name: 'Cuerpo técnico',
    description: 'Tu club {club} compitió con {n} nadadores en {temporada}.',
    how: 'Entrena un club con 5 o más nadadores que compitan en la temporada.',
    compare: 'none',
    levels: one('R'),
    params: { minSwimmers: 5 },
    repeatable: true,
    accountOnly: true,
    evaluator: 'season_staff',
  },
  {
    key: 'good_vibes',
    group: 'comunidad',
    sports: 'all',
    scope: 'cuenta',
    period: 'siempre',
    category: 'companerismo',
    shape: 'square',
    icon: 'party-popper',
    name: 'Buena vibra',
    description: 'Felicitaste a {n} compañeros distintos por sus juegos.',
    how: 'Felicita a {n} compañeros distintos de tus ligas, a lo largo de varios meses.',
    unit: units('persona', 'personas'),
    compare: 'gte',
    levels: tiers('C PC R', [10, 30, 75], [{ req: { months: 2 } }, { req: { months: 3 } }, { req: { months: 6 } }]),
    accountOnly: true,
    noMinors: true,
    evaluator: 'community',
  },
  {
    key: 'bowlingx_roots',
    group: 'comunidad',
    sports: ['bowling'],
    scope: 'cuenta',
    period: 'siempre',
    category: 'historia',
    shape: 'square',
    icon: 'tree-palm',
    name: 'Raíces BowlingX',
    description: 'Estabas desde BowlingX. Aquí empezó todo.',
    how: 'Solo para quienes venían de BowlingX y jugaron en MatchMate.',
    compare: 'none',
    levels: one('cerrada'),
    accountOnly: true,
    closed: true,
    evaluator: 'community',
  },
];

// ---------------------------------------------------------------------------------------------------------
// El catálogo

export const BADGES: readonly BadgeDef[] = [
  ...GENERAL,
  ...BOWLING,
  ...RACKET_BADGES,
  ...TEAM_BADGES,
  ...BASKETBALL,
  ...FOOTBALL_BADGES,
  ...GOLF,
  ...SWIMMING,
  ...MONTHLY,
  ...YEARLY,
  ...SEASON,
  ...COMMUNITY,
];

const BY_KEY: ReadonlyMap<string, BadgeDef> = new Map(BADGES.map((b) => [b.key, b]));

export const BADGE_KEYS: readonly string[] = BADGES.map((b) => b.key);

/** Mismo formato que el check de `badge_awards.badge_key`. */
export const BADGE_KEY_RE = /^[a-z][a-z0-9_]{1,39}$/;

export const isBadgeKey = (key: unknown): key is string => typeof key === 'string' && BY_KEY.has(key);

/** La definición de una key; undefined si esta versión no la conoce (una fila de una versión más nueva). */
export const badgeDef = (key: string): BadgeDef | undefined => BY_KEY.get(key);

/** Cuántas definiciones (niveles) suman unas insignias. El catálogo completo da 197. */
export const definitionCount = (defs: readonly BadgeDef[] = BADGES): number => defs.reduce((n, d) => n + d.levels.length, 0);

/** Deportes de una insignia como van en la fila (`['all']` para las de cuenta sin deporte). */
export const badgeSports = (def: BadgeDef): BadgeSport[] => (def.sports === 'all' ? ['all'] : [...def.sports]);

/** Las insignias que existen para un deporte (o las de cuenta sin deporte, con 'all'). */
export const badgesForSport = (sport: BadgeSport): BadgeDef[] =>
  BADGES.filter((d) => (sport === 'all' ? d.sports === 'all' : d.sports !== 'all' && d.sports.includes(sport)));

/** Las insignias que se apagan o no con `badges_auto` en una liga (las de cuenta no dependen de eso). */
export function allowedBy(def: BadgeDef, mode: BadgesAuto): boolean {
  if (def.scope === 'cuenta') return true;
  if (mode === 'ninguna') return false;
  return mode === 'todas' || !def.title;
}

// ---------------------------------------------------------------------------------------------------------
// Valores por deporte o variante

/**
 * Variantes de una fila, de la más específica a la más general: baloncesto 3x3 → `['basketball3x3',
 * 'basketball']`; golf de 9 hoyos → `['golf9', 'golf']`; 'all' → `[]` (solo `default`).
 */
export function variantsOf(sport: BadgeSport, opts: { is3x3?: boolean; nineHoles?: boolean } = {}): Variant[] {
  if (sport === 'all') return [];
  if (sport === 'basketball' && opts.is3x3) return ['basketball3x3', 'basketball'];
  if (sport === 'golf' && opts.nineHoles) return ['golf9', 'golf'];
  return [sport];
}

const isByVariantObject = <T>(v: ByVariant<T>): v is Readonly<Partial<Record<Variant | 'default', T>>> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

/** El valor para esas variantes: el primero que exista, si no `default`; undefined si no hay. */
export function pickVariant<T>(value: ByVariant<T> | undefined, variants: readonly Variant[]): T | undefined {
  if (value === undefined) return undefined;
  if (!isByVariantObject(value)) return value as T;
  for (const v of variants) if (value[v] !== undefined) return value[v];
  return value.default;
}

/** Deporte de la fila, una variante ('basketball3x3', 'golf9') o la lista ya armada con `variantsOf`. */
export type VariantArg = BadgeSport | Variant | readonly Variant[];

function variantList(arg: VariantArg | undefined): readonly Variant[] {
  if (arg === undefined || arg === 'all') return [];
  if (typeof arg !== 'string') return arg;
  if (arg === 'basketball3x3') return ['basketball3x3', 'basketball'];
  if (arg === 'golf9') return ['golf9', 'golf'];
  return [arg];
}

/** Un parámetro del criterio (`params`) para un deporte o variante. */
export const paramOf = (def: BadgeDef, name: string, sport?: VariantArg): number | undefined => pickVariant(def.params?.[name], variantList(sport));

// ---------------------------------------------------------------------------------------------------------
// Niveles

/** Nombre corto de cada nivel (el metal); «Única» para las de un solo nivel. */
export const LEVEL_LABEL: Readonly<Record<Level, string>> = { 0: 'Única', 1: 'Bronce', 2: 'Plata', 3: 'Oro', 4: 'Platino', 5: 'Diamante' };

/** Metal con que se pinta cada nivel (§4.3): la única se pinta en oro, sin puntos. */
export const LEVEL_TIER: Readonly<Record<Level, 'bronce' | 'plata' | 'oro' | 'platino' | 'diamante'>> = {
  0: 'oro',
  1: 'bronce',
  2: 'plata',
  3: 'oro',
  4: 'platino',
  5: 'diamante',
};

export const levelDef = (def: BadgeDef, level: Level): LevelDef | undefined => def.levels.find((l) => l.level === level);

/** Umbral de un nivel para esas variantes (el puesto en los podios). */
export const thresholdOf = (def: BadgeDef, level: Level, sport?: VariantArg): number | undefined =>
  pickVariant(levelDef(def, level)?.threshold, variantList(sport));

/** Rareza estimada de un nivel en un deporte. */
export const rarityOf = (def: BadgeDef, level: Level, sport?: VariantArg): RarityTarget | undefined =>
  pickVariant(levelDef(def, level)?.rarity, variantList(sport));

/** ¿El valor llega al nivel? (`gte`: llega al umbral; `lt`: queda por debajo; sin umbral: no se mide así). */
function reaches(def: BadgeDef, l: LevelDef, value: number, variants: readonly Variant[]): boolean {
  const t = pickVariant(l.threshold, variants);
  if (t === undefined) return false;
  if (def.compare === 'gte') return value >= t;
  if (def.compare === 'lt') return value < t;
  if (def.compare === 'place') return value === t;
  return false;
}

/** Todos los niveles que alcanza un valor (cada nivel es una fila propia), de menor a mayor. */
export function levelsReached(def: BadgeDef, value: number, sport?: VariantArg): Level[] {
  const variants = variantList(sport);
  return def.levels.filter((l) => reaches(def, l, value, variants)).map((l) => l.level);
}

/** El nivel más alto que alcanza un valor; null si ninguno. */
export function levelFor(def: BadgeDef, value: number, sport?: VariantArg): Level | null {
  const got = levelsReached(def, value, sport);
  return got.length ? got[got.length - 1] : null;
}

/** El siguiente nivel que falta y su umbral (para `badge_progress`); null si ya tiene el más alto o no se mide. */
export function nextLevel(def: BadgeDef, value: number, sport?: VariantArg): { level: Level; target: number } | null {
  if (def.compare !== 'gte' && def.compare !== 'lt') return null;
  const variants = variantList(sport);
  for (const l of def.levels) {
    if (reaches(def, l, value, variants)) continue;
    const target = pickVariant(l.threshold, variants);
    return target === undefined ? null : { level: l.level, target };
  }
  return null;
}

/** Nivel de un puesto en un podio: 1.º oro (3), 2.º plata (2), 3.º bronce (1). */
export function placeLevel(place: number): Level | null {
  return place === 1 ? 3 : place === 2 ? 2 : place === 3 ? 1 : null;
}

/** ¿Esta insignia (o esta cara) pide aval? */
export const needsAval = (def: BadgeDef, alt?: string | null): boolean => !!def.aval || (!!alt && !!def.alts?.[alt]?.aval);

// ---------------------------------------------------------------------------------------------------------
// Textos

/** Nombres de las categorías, en el orden en que salen en el perfil (§6.1). */
export const CATEGORY_LABEL: Readonly<Record<BadgeCategory, string>> = {
  resultados: 'Resultados',
  marcas: 'Marcas',
  hitos: 'Hitos',
  mejora: 'Mejora',
  constancia: 'Constancia',
  asistencia: 'Asistencia',
  juego_limpio: 'Juego limpio',
  bienvenida: 'Bienvenida',
  multideporte: 'Multideporte',
  lealtad: 'Lealtad',
  organizacion: 'Organización',
  voluntariado: 'Voluntariado',
  liderazgo: 'Liderazgo',
  companerismo: 'Compañerismo',
  historia: 'Historia',
};

export const CATEGORY_ORDER: readonly BadgeCategory[] = Object.keys(CATEGORY_LABEL) as BadgeCategory[];

/** Secciones de la vitrina del perfil (§6.1), en orden; cada categoría cae en una. */
export const PROFILE_SECTIONS = ['Resultados', 'Marcas', 'Hitos', 'Constancia', 'Asistencia', 'Juego limpio', 'Comunidad'] as const;
export type ProfileSection = (typeof PROFILE_SECTIONS)[number];

export const SECTION_OF: Readonly<Record<BadgeCategory, ProfileSection>> = {
  resultados: 'Resultados',
  marcas: 'Marcas',
  mejora: 'Marcas',
  hitos: 'Hitos',
  bienvenida: 'Hitos',
  multideporte: 'Hitos',
  constancia: 'Constancia',
  lealtad: 'Constancia',
  asistencia: 'Asistencia',
  juego_limpio: 'Juego limpio',
  organizacion: 'Comunidad',
  voluntariado: 'Comunidad',
  liderazgo: 'Comunidad',
  companerismo: 'Comunidad',
  historia: 'Comunidad',
};

/**
 * Lo que puede ir entre llaves en un texto del catálogo. `{n}` es el número principal; `{valor}` una línea de
 * evidencia ya armada («promedio 187 en 12 juegos», «+9 pinos»); `{nivel}` el nombre del nivel; `{unidad}` lo que
 * se juega en el deporte (juego, partido, ronda, prueba); `{deportes}` la lista («boliche, pádel y fútbol»).
 */
export const PLACEHOLDERS = [
  'n',
  'valor',
  'nivel',
  'deporte',
  'deportes',
  'deportes_n',
  'unidad',
  'liga',
  'evento',
  'categoria',
  'mes',
  'anio',
  'temporada',
  'meses',
  'equipo',
  'jugados',
  'total',
  'fechas',
  'jugadores',
  'campo',
  'hoyos',
  'prueba',
  'club',
  'caja',
  'formato',
  'tope',
] as const;
export type Placeholder = (typeof PLACEHOLDERS)[number];

/** Rellena `{clave}` con los valores; lo que no viene se queda como está. */
export function fillText(template: string, vars: Readonly<Partial<Record<Placeholder, string | number>>>): string {
  return template.replace(/\{([a-z_]+)\}/g, (all, k: string) => {
    const v = vars[k as Placeholder];
    return v === undefined ? all : String(v);
  });
}

/** Las llaves que usa un texto. */
export const placeholdersIn = (template: string): string[] => [...template.matchAll(/\{([a-z_]+)\}/g)].map((m) => m[1]);

export interface TextOptions {
  sport?: BadgeSport;
  /** Variantes ya resueltas (3x3, 9 hoyos); si no, las del deporte. */
  variants?: readonly Variant[];
  level?: Level;
  /** Cara de la insignia (`context.alt`). */
  alt?: string | null;
}

const optVariants = (o: TextOptions) => o.variants ?? variantsOf(o.sport ?? 'all');
const altOf = (def: BadgeDef, alt: string | null | undefined): BadgeAlt | undefined => (alt ? def.alts?.[alt] : undefined);

/** Nombre de la insignia (plantilla: `year_recap` lleva `{anio}`). */
export function nameOf(def: BadgeDef, o: TextOptions = {}): string {
  return altOf(def, o.alt)?.name ?? pickVariant(def.name, optVariants(o)) ?? def.key;
}

/** Nombre del nivel: el propio ('Pavo', 'Primer lugar') o el metal. */
export function levelNameOf(def: BadgeDef, level: Level, o: Omit<TextOptions, 'level'> = {}): string {
  return pickVariant(def.levelNames?.[level], optVariants(o)) ?? LEVEL_LABEL[level];
}

/** Descripción (plantilla) de lo que se ganó. */
export function descriptionOf(def: BadgeDef, o: TextOptions = {}): string {
  const v = optVariants(o);
  return (
    altOf(def, o.alt)?.description ??
    (o.level !== undefined ? pickVariant(def.levelDescriptions?.[o.level], v) : undefined) ??
    pickVariant(def.description, v) ??
    ''
  );
}

/** Cómo se gana (plantilla), para las bloqueadas. */
export const howOf = (def: BadgeDef, o: Omit<TextOptions, 'level' | 'alt'> = {}): string => pickVariant(def.how, optVariants(o)) ?? '';

/** Unidad del progreso en singular o plural según `n` («Te faltan 3 juegos»). */
export function unitOf(def: BadgeDef, n: number, o: Omit<TextOptions, 'level' | 'alt'> = {}): string {
  const u = pickVariant(def.unit, optVariants(o));
  return u ? (n === 1 ? u[0] : u[1]) : '';
}

// ---------------------------------------------------------------------------------------------------------
// Motor: qué evaluador corre con cada trabajo de la cola

/** Trabajos de la cola (§3.3) que corren cada evaluador. `historial` = la primera corrida (§3.5). */
export const EVALUATOR_JOBS: Readonly<Record<EvaluatorId, readonly JobKind[]>> = {
  debut: ['resultado', 'revisar', 'vinculo', 'historial'],
  account_activity: ['cuenta', 'vinculo', 'historial'],
  month_streak: ['mes', 'vinculo', 'historial'],
  climbing: ['resultado', 'revisar', 'vinculo', 'historial'],
  event_podium: ['evento', 'historial'],
  bowling_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  bowling_game: ['resultado', 'revisar', 'historial'],
  bowling_event: ['evento', 'historial'],
  racket_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  racket_match: ['resultado', 'revisar', 'historial'],
  racket_night: ['noche', 'historial'],
  team_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  team_match: ['resultado', 'revisar', 'historial'],
  basketball_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  basketball_match: ['resultado', 'revisar', 'historial'],
  football_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  football_match: ['resultado', 'revisar', 'historial'],
  golf_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  golf_card: ['resultado', 'revisar', 'historial'],
  swim_career: ['resultado', 'revisar', 'vinculo', 'historial'],
  swim_meet: ['evento', 'historial'],
  month_league: ['mes', 'historial'],
  month_account: ['mes', 'historial'],
  box_month: ['cajas'],
  ladder_month: ['escalera'],
  year_account: ['anio', 'historial'],
  year_league: ['anio', 'historial'],
  // Sin historial: no hay temporadas pasadas (§3.5).
  season_league: ['temporada'],
  season_staff: ['temporada'],
  community: ['cuenta', 'historial'],
};

/** Los evaluadores que corre un tipo de trabajo. */
export const evaluatorsFor = (kind: JobKind): EvaluatorId[] =>
  (Object.keys(EVALUATOR_JOBS) as EvaluatorId[]).filter((id) => EVALUATOR_JOBS[id].includes(kind));

/** Las insignias de un evaluador. */
export const badgesOfEvaluator = (id: EvaluatorId): BadgeDef[] => BADGES.filter((d) => d.evaluator === id);
